tab -> space
git-svn-id: svn://svn.uzsolt.hu/maintainport/trunk@49 8ee7907a-f19a-e711-a987-005056a07bed

diff --git a/maintainport b/maintainport
--- a/maintainport
+++ b/maintainport
@@ -26,115 +26,115 @@ WORKINGDIR=""
 message() {
   MSG=$1
   shift
-	printf "${yellow}>>${white} ${MSG} ${end}\n" $*
+  printf "${yellow}>>${white} ${MSG} ${end}\n" $*
 }
 
 # Print and read a simple question
 question() {
-	printf "${green}$*${end}\n" >&2
-	read X
-	echo $X
+  printf "${green}$*${end}\n" >&2
+  read X
+  echo $X
 }
 
 wait_for_enter() {
-	MSG=${1:-Please press ENTER.}
-	message "${MSG}"
-	read X
+  MSG=${1:-Please press ENTER.}
+  message "${MSG}"
+  read X
 }
 
 # Print an error message into stderr
 error() {
-	local first=$1
-	shift
-	printf "${bred}!! ${red}${first}${end}\n" $* >&2
+  local first=$1
+  shift
+  printf "${bred}!! ${red}${first}${end}\n" $* >&2
 }
 
 init() {
-	CONF=~/.maintainport.conf
-	[ -f ${CONF} -a -r ${CONF} ] && . ${CONF}
-	EDITOR=${EDITOR:-vi}
-	SHELL=${SHELL:-/bin/tcsh}
-	PAGER=${PAGER:-"less -R"}
+  CONF=~/.maintainport.conf
+  [ -f ${CONF} -a -r ${CONF} ] && . ${CONF}
+  EDITOR=${EDITOR:-vi}
+  SHELL=${SHELL:-/bin/tcsh}
+  PAGER=${PAGER:-"less -R"}
 
-	VCS="${VCS:-svnlite}"
-	VCS_STATUS="${VCS_STATUS:-status}"
-	VCS_DIFF="${VCS_DIFF:-diff}"
-	VCS_REVERT="${VCS_REVERT:-revert --recursive}"
+  VCS="${VCS:-svnlite}"
+  VCS_STATUS="${VCS_STATUS:-status}"
+  VCS_DIFF="${VCS_DIFF:-diff}"
+  VCS_REVERT="${VCS_REVERT:-revert --recursive}"
 
-	P_PORTSDIR=${P_PORTSDIR:-/usr/local/poudriere/ports/}
-	P_PORT=${P_PORT:-default}
-	P_LOGDIR=${P_LOGDIR:-/usr/local/poudriere/data/logs/bulk/}
+  P_PORTSDIR=${P_PORTSDIR:-/usr/local/poudriere/ports/}
+  P_PORT=${P_PORT:-default}
+  P_LOGDIR=${P_LOGDIR:-/usr/local/poudriere/data/logs/bulk/}
   P_PACKDIR=${P_PACKDIR:-/usr/local/poudriere/data/packages/}
 
-	WWW_LOGDIR=${WWW_LOGDIR:-/usr/local/www/freebsd/logs/}
-	WWW_DIFFDIR=${WWW_DIFFDIR:-/usr/local/www/freebsd/diff/}
+  WWW_LOGDIR=${WWW_LOGDIR:-/usr/local/www/freebsd/logs/}
+  WWW_DIFFDIR=${WWW_DIFFDIR:-/usr/local/www/freebsd/diff/}
   WWW_TESTPACKAGEDIR=${WWW_TESTPACKAGEDIR:-/usr/local/www/freebsd/test_pkg/}
 
   PACK_SUFFIX=${PACK_SUFFIX:-.txz}
 
-	MSG=0
-	if which -s poudriere; then
-		POUDRIERE=poudriere
-	else
-		POUDRIERE=""
-		MSG=1
-		error "${STR_MISSED_POUDRIERE}"
-	fi
+  MSG=0
+  if which -s poudriere; then
+    POUDRIERE=poudriere
+  else
+    POUDRIERE=""
+    MSG=1
+    error "${STR_MISSED_POUDRIERE}"
+  fi
 
-	if which -s colordiff; then
-		COLORDIFF="colordiff"
-	else
-		COLORDIFF="cat"
-		MSG=1
-		message "${STR_MISSED_COLORDIFF}"
-	fi
+  if which -s colordiff; then
+    COLORDIFF="colordiff"
+  else
+    COLORDIFF="cat"
+    MSG=1
+    message "${STR_MISSED_COLORDIFF}"
+  fi
 
-	if which -s portlint; then
-		PORTLINT=portlint
-	else
-		PORTLINT=""
-		MSG=1
-		error "${STR_MISSED_PORTLINT}"
-	fi
+  if which -s portlint; then
+    PORTLINT=portlint
+  else
+    PORTLINT=""
+    MSG=1
+    error "${STR_MISSED_PORTLINT}"
+  fi
 
-	if [ ${MSG} -gt 0 ]; then
-		wait_for_enter
-	fi
+  if [ ${MSG} -gt 0 ]; then
+    wait_for_enter
+  fi
 }
 
 # Check if ${PORTSDIR}/${PORT} exist
 # Params:
 # return 1 if isn't valid else 0
 check_port() {
-	if echo ${PORT} | grep -qvx "[[:alnum:]-]\+/[[:alnum:]-]\+"; then
-		error "${STR_BAD_CATPORT_STYLE}" "${PORT}"
-		exit 1
-	fi
-	WORKINGDIR=${P_PORTSDIR}/${P_PORT}/${PORT}
-	if [ ! -d ${WORKINGDIR} ]; then
-		error "${STR_PORT_NOTEXIST}" "${PORT}" "${P_PORTSDIR}/${P_PORT}"
-		exit 1
-	fi
+  if echo ${PORT} | grep -qvx "[[:alnum:]-]\+/[[:alnum:]-]\+"; then
+    error "${STR_BAD_CATPORT_STYLE}" "${PORT}"
+    exit 1
+  fi
+  WORKINGDIR=${P_PORTSDIR}/${P_PORT}/${PORT}
+  if [ ! -d ${WORKINGDIR} ]; then
+    error "${STR_PORT_NOTEXIST}" "${PORT}" "${P_PORTSDIR}/${P_PORT}"
+    exit 1
+  fi
 }
 
 # Parse parameters
 # Runs check_port for valid port.
 parse_params() {
-	PORT=$1
-	if [ $# -lt 1 ]; then
-		error "Missing port"
-		exit 1
-	fi
+  PORT=$1
+  if [ $# -lt 1 ]; then
+    error "Missing port"
+    exit 1
+  fi
 
-	check_port
+  check_port
 }
 
 get_poudriere_jails() {
-	${POUDRIERE} jail -l | sed -n '2,$ s| .*||p'
+  ${POUDRIERE} jail -l | sed -n '2,$ s| .*||p'
 }
 
 get_pkgname() {
-	make -VPKGNAME -C ${WORKINGDIR} $*
+  make -VPKGNAME -C ${WORKINGDIR} $*
 }
 
 get_pkgname_flavor() {
@@ -151,114 +151,114 @@ get_pkgplist() {
 
 # Check if port is changed.
 port_changed() {
-	CURDIR=`pwd`
-	cd ${WORKINGDIR}
-	if ${VCS} ${VCS_STATUS} . | grep -q ".*"; then
-		echo " (modified)"
-	fi 
-	cd ${CURDIR}
+  CURDIR=`pwd`
+  cd ${WORKINGDIR}
+  if ${VCS} ${VCS_STATUS} . | grep -q ".*"; then
+    echo " (modified)"
+  fi 
+  cd ${CURDIR}
 }
 
 menu_main() {
-	MODIFIED=`port_changed`
-	exec 3>&1
-	CHOICE=`dialog --title "${PORT}${MODIFIED}" \
-	--no-cancel --default-item ${DEFAULT_ITEM} \
-	--menu "Choose an option" 20 60 17 \
-		M "Edit Makefile" \
-		D "Update distinfo (make makesum)" \
-		L "Run portlint" \
-		T "Run poudriere testport" \
-		C "Configure and run poudriere testport" \
+  MODIFIED=`port_changed`
+  exec 3>&1
+  CHOICE=`dialog --title "${PORT}${MODIFIED}" \
+  --no-cancel --default-item ${DEFAULT_ITEM} \
+  --menu "Choose an option" 20 60 17 \
+    M "Edit Makefile" \
+    D "Update distinfo (make makesum)" \
+    L "Run portlint" \
+    T "Run poudriere testport" \
+    C "Configure and run poudriere testport" \
     F "Edit pkg-plist (files)" \
-		V "View diff" \
-		S "Run shell" \
-		P "Create testpackage" \
-		R "Report" \
-		X "Revert changes" \
-		Q "Quit" 2>&1 1>&3`
-	if [ $? -gt 0 ]; then return 1 ; fi
-	DEFAULT_ITEM=${CHOICE}
-	case ${CHOICE} in
-		M)
+    V "View diff" \
+    S "Run shell" \
+    P "Create testpackage" \
+    R "Report" \
+    X "Revert changes" \
+    Q "Quit" 2>&1 1>&3`
+  if [ $? -gt 0 ]; then return 1 ; fi
+  DEFAULT_ITEM=${CHOICE}
+  case ${CHOICE} in
+    M)
       ( cd ${WORKINGDIR} && ${EDITOR} Makefile )
-			;;
-		D)
-			message "Updating distinfo..."
-			make makesum -C ${WORKINGDIR}
-			if [ $? -gt 0 ]; then
-				error "An error occured."
-				wait_for_enter
-			fi
-			;;
-		L)
-			if [ -z "${PORTLINT}" ]; then
-				error "${STR_MISSED_PORTLINT}"
+      ;;
+    D)
+      message "Updating distinfo..."
+      make makesum -C ${WORKINGDIR}
+      if [ $? -gt 0 ]; then
+        error "An error occured."
         wait_for_enter
-			else
+      fi
+      ;;
+    L)
+      if [ -z "${PORTLINT}" ]; then
+        error "${STR_MISSED_PORTLINT}"
+        wait_for_enter
+      else
         (
           export PORTSDIR=${P_PORTSDIR}/${P_PORT}
           ${PORTLINT} -abcmt ${WORKINGDIR} | ${PAGER}
         )
-			fi
-			;;
-		T)
-			menu_poudriere
-			;;
-		C)
-			menu_poudriere -c
-			;;
+      fi
+      ;;
+    T)
+      menu_poudriere
+      ;;
+    C)
+      menu_poudriere -c
+      ;;
     F)
       (
         export PORTSDIR=${P_PORTSDIR}/${P_PORT}
         cd ${WORKINGDIR} && ${EDITOR} `get_pkgplist` )
       ;;
-		V)
-			view_diff | ${PAGER}
-			;;
-		S)
-			cd ${WORKINGDIR}
-			${SHELL} -l
-			;;
-		P)
-			build_test_package
-			;;
-		R)
-			create_report
-			;;
-		X)
-			revert_changes
-			;;
-		Q)
-			return 1
-			;;
-	esac
-	return 0
+    V)
+      view_diff | ${PAGER}
+      ;;
+    S)
+      cd ${WORKINGDIR}
+      ${SHELL} -l
+      ;;
+    P)
+      build_test_package
+      ;;
+    R)
+      create_report
+      ;;
+    X)
+      revert_changes
+      ;;
+    Q)
+      return 1
+      ;;
+  esac
+  return 0
 
 }
 
 create_diff() {
-	CURDIR=`pwd`
-	cd ${WORKINGDIR}
-	${VCS} ${VCS_DIFF} .
-	cd ${CURDIR}
+  CURDIR=`pwd`
+  cd ${WORKINGDIR}
+  ${VCS} ${VCS_DIFF} .
+  cd ${CURDIR}
 }
 
 view_diff() {
 # TODO svn status
-	create_diff | ${COLORDIFF}
+  create_diff | ${COLORDIFF}
 }
 
 # Return values:
 # JAIL variable will store the jail name
 menu_choose_jail() {
-	JAILS=`get_poudriere_jails`
-	JAILS_NR=`echo ${JAILS} | tr ' ' '\n' | cat -n`
-	exec 3>&1
-	CHOICE=`dialog --title "${PORT}" --menu "Which jail?" 15 40 4 ${JAILS_NR} 2>&1 1>&3`
-	result=$?
-	JAIL=`echo ${JAILS} | tr ' ' '\n' | sed -n "${CHOICE}p"`
-	return ${result}
+  JAILS=`get_poudriere_jails`
+  JAILS_NR=`echo ${JAILS} | tr ' ' '\n' | cat -n`
+  exec 3>&1
+  CHOICE=`dialog --title "${PORT}" --menu "Which jail?" 15 40 4 ${JAILS_NR} 2>&1 1>&3`
+  result=$?
+  JAIL=`echo ${JAILS} | tr ' ' '\n' | sed -n "${CHOICE}p"`
+  return ${result}
 }
 
 # Return values:
@@ -288,24 +288,24 @@ menu_before_poudriere() {
 # Params:
 # $1 - additional options to poudriere
 menu_poudriere() {
-	if [ -z "${POUDRIERE}" ]; then
-		error "${STR_MISSED_POUDRIERE}"
+  if [ -z "${POUDRIERE}" ]; then
+    error "${STR_MISSED_POUDRIERE}"
     wait_for_enter
-	else
+  else
     menu_before_poudriere
-		if [ $? -gt 0 ]; then return 1; fi
-		run_poudriere ${JAIL} $1
-	fi
+    if [ $? -gt 0 ]; then return 1; fi
+    run_poudriere ${JAIL} $1
+  fi
 }
 
 # Params:
 # $1 - which jail
 # $2 - additional options
 run_poudriere() {
-	message "${STR_POUDRIERE_START}" "${JAIL}"
-	${POUDRIERE} testport $2 -j ${1} -p ${P_PORT} ${PORT}${FLAVOR_AT}
-	RET=$?
-	message "${STR_POUDRIERE_FINISHED}" "${JAIL}" "${RET}"
+  message "${STR_POUDRIERE_START}" "${JAIL}"
+  ${POUDRIERE} testport $2 -j ${1} -p ${P_PORT} ${PORT}${FLAVOR_AT}
+  RET=$?
+  message "${STR_POUDRIERE_FINISHED}" "${JAIL}" "${RET}"
   process_logfile
 }
 
@@ -372,46 +372,46 @@ process_missings() {
 # $1 - which jail
 build_test_package() {
   menu_before_poudriere || return 1
-	message "Build ${PORT} package in ${JAIL}"
-	${POUDRIERE} bulk -B test_package/`date +%Y%m%d-%H%M` -j ${JAIL} -p ${P_PORT} ${PORT}
-	if [ $? -eq 0 ]; then
-		message "${STR_COPY_PACKAGE}" "${WWW_TESTPACKAGEDIR}"
-		cp ${P_PACKDIR}/${JAIL}-${P_PORT}/All/`get_pkgname_flavor`${PACK_SUFFIX} ${WWW_TESTPACKAGEDIR}
-	fi
-	wait_for_enter
+  message "Build ${PORT} package in ${JAIL}"
+  ${POUDRIERE} bulk -B test_package/`date +%Y%m%d-%H%M` -j ${JAIL} -p ${P_PORT} ${PORT}
+  if [ $? -eq 0 ]; then
+    message "${STR_COPY_PACKAGE}" "${WWW_TESTPACKAGEDIR}"
+    cp ${P_PACKDIR}/${JAIL}-${P_PORT}/All/`get_pkgname_flavor`${PACK_SUFFIX} ${WWW_TESTPACKAGEDIR}
+  fi
+  wait_for_enter
 }
 
 # Params
 # $1 runned jail
 copy_logfile() {
-	if [ -e "${LOGFILE}" ]; then
-		DESTLOGDIR=${WWW_LOGDIR}/${PORT}/${JAIL}-${P_PORT}/
-		message "${STR_COPY_LOGFILE}" "${DESTLOGDIR}"
-		SUFFIX=`question "${STR_SUFFIX_LOGFILE}"`
-		mkdir -p ${DESTLOGDIR}
-		cp ${LOGFILE} ${DESTLOGDIR}/`get_pkgname_flavor`${SUFFIX}.log
-	else
-		error "${STR_LOGFILE_NOTEXIST}" "${LOGFILE}"
-	fi
+  if [ -e "${LOGFILE}" ]; then
+    DESTLOGDIR=${WWW_LOGDIR}/${PORT}/${JAIL}-${P_PORT}/
+    message "${STR_COPY_LOGFILE}" "${DESTLOGDIR}"
+    SUFFIX=`question "${STR_SUFFIX_LOGFILE}"`
+    mkdir -p ${DESTLOGDIR}
+    cp ${LOGFILE} ${DESTLOGDIR}/`get_pkgname_flavor`${SUFFIX}.log
+  else
+    error "${STR_LOGFILE_NOTEXIST}" "${LOGFILE}"
+  fi
 }
 
 create_report() {
-	message "${STR_COPY_DIFF}" "${WWW_DIFFDIR}"
-	mkdir -p ${WWW_DIFFDIR}/${PORT}
-	create_diff > ${WWW_DIFFDIR}/${PORT}/`get_pkgname`.diff
-	wait_for_enter
+  message "${STR_COPY_DIFF}" "${WWW_DIFFDIR}"
+  mkdir -p ${WWW_DIFFDIR}/${PORT}
+  create_diff > ${WWW_DIFFDIR}/${PORT}/`get_pkgname`.diff
+  wait_for_enter
 }
 
 revert_changes() {
-	dialog --title "Confirmation" --yesno "Are you sure to revert ${PORT}?" 5 50
-	if [ $? -eq 0 ]; then
-		message "Reverting ${WORKINGDIR}..."
-		CURDIR=`pwd`
-		cd ${WORKINGDIR}
-		${VCS} ${VCS_REVERT} .
-		cd ${CURDIR}
-		wait_for_enter
-	fi
+  dialog --title "Confirmation" --yesno "Are you sure to revert ${PORT}?" 5 50
+  if [ $? -eq 0 ]; then
+    message "Reverting ${WORKINGDIR}..."
+    CURDIR=`pwd`
+    cd ${WORKINGDIR}
+    ${VCS} ${VCS_REVERT} .
+    cd ${CURDIR}
+    wait_for_enter
+  fi
 }
 
 init
